%if HAU_USE_CONTAINER == HAU_BOOLEAN_TRUE
 %ifndef HAU_OPERATING_SYSTEM
  __HAU_ERROR_DEFINITION_Not_Defined "HAU_OPERATING_SYSTEM"
 %endif

 %ifndef HAU_BIT_CLASS
  __HAU_ERROR_DEFINITION_Not_Defined "HAU_BIT_CLASS"
 %endif

 %ifndef HAU_ARCHITECTURE
  __HAU_ERROR_DEFINITION_Not_Defined "HAU_ARCHITECTURE"
 %endif

%endif
