
%ifndef HAU_ASSEMBLER
 __HAU_ERROR_DEFINITION_Not_Defined "HAU_ASSEMBLER"
%elifidn HAU_ASSEMBLER, __HAU_DEFINITIONS_ASSEMBLERS_NASM
%else
 __HAU_ERROR_DEFINITION_Invalid_Value_Text "HAU_ASSEMBLER", HAU_ASSEMBLER, USE DEFINITIONS:, "__HAU_DEFINITIONS_ASSEMBLERS_NASM"
%endif

%ifndef HAU_USE_CONTAINER
 __HAU_ERROR_DEFINITION_Not_Defined "HAU_USE_CONTAINER"
%elif HAU_USE_CONTAINER == __HAU_BOOLEAN_TRUE
%elif HAU_USE_CONTAINER != __HAU_BOOLEAN_FALSE
 __HAU_ERROR_DEFINITION_Invalid_Value_Text "HAU_USE_CONTAINER", HAU_USE_CONTAINER, USE BOOLEANS:, "__HAU_BOOLEAN_TRUE", "__HAU_BOOLEAN_FALSE"
%endif
