
%ifndef HAU_ASSEMBLER
 __HAU_ERROR_DEFINITION_Not_Defined "HAU_ASSEMBLER"
%elifidn HAU_ASSEMBLER, __HAU_DEFINITIONS_ASSEMBLERS_NASM
%else
 __HAU_ERROR_DEFINITION_Invalid_Value_Text "HAU_ASSEMBLER", HAU_ASSEMBLER, USE DEFINITIONS:, "__HAU_DEFINITIONS_ASSEMBLERS_NASM"
%endif
